# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Qjh9pl3V4bQ7voKuH1-24XWwfwWYKev
"""

#Loading dataset

import pandas as pd

df = pd.read_excel("Online Retail.xlsx")

print(df.shape)
df.head()

#Data Cleaning

# Remove null customer IDs
df = df.dropna(subset=['CustomerID'])

# Remove negative quantity (returns)
df = df[df['Quantity'] > 0]

# Remove missing prices
df = df[df['UnitPrice'] > 0]

# Create revenue column
df['Revenue'] = df['Quantity'] * df['UnitPrice']

#EDA

df.describe()
df['Country'].value_counts().head()
df['Description'].value_counts().head(10)

#Visualization

import matplotlib.pyplot as plt

df['Revenue'].hist(bins=50)
plt.title("Revenue Distribution")
plt.show()

#Top product

top_products = df.groupby('Description')['Revenue'].sum().sort_values(ascending=False).head(10)
top_products.plot(kind='bar')
plt.title("Top Products by Revenue")
plt.show()

#Monthly Sales Trend

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['Month'] = df['InvoiceDate'].dt.to_period('M')

monthly_sales = df.groupby('Month')['Revenue'].sum()
monthly_sales.plot()
plt.title("Monthly Sales Trend")
plt.show()

#Pandas Period

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['Month'] = df['InvoiceDate'].dt.strftime('%Y-%m')

#Creating SQLite Database

import sqlite3

conn = sqlite3.connect("retail.db")

df.to_sql("sales", conn, if_exists="replace", index=False)

#Top 5 products

query = """
SELECT Description,
       SUM(Quantity * UnitPrice) AS Revenue
FROM sales
GROUP BY Description
ORDER BY Revenue DESC
LIMIT 5;
"""

result = pd.read_sql(query, conn)
result

#Monthly Sales

query = """
SELECT substr(InvoiceDate, 1, 7) AS Month,
       SUM(Quantity * UnitPrice) AS Revenue
FROM sales
GROUP BY Month
ORDER BY Month;
"""

pd.read_sql(query, conn)